include:
  - ./docker-compose-base.yml

services:
  tiny_rag:
    depends_on:
      es:
        condition: service_healthy
    image: tiny_rag:dev
    container_name: tiny_rag_server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./tiny_rag_logs:/tiny_rag/logs
      - ./data_folder:/tiny_rag/data_folder
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS:-1}
      - LIGHTEN=${LIGHTEN:-1}
    networks:
      - tiny_rag
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  