include:
  - ./docker-compose-base.yml

services:
  my_rag:
    depends_on:
      redis:
        condition: service_healthy
    image: my_rag:dev
    container_name: my_rag_server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./my_rag_logs:/my_rag/logs
      - ./data_folder:/my_rag/data_folder
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS:-1}
      - LIGHTEN=${LIGHTEN:-1}
    networks:
      - my_rag
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  